pull_request_rules:
    - name: Automatic merge on update by renovate
      actions:
        merge:
          strict: smart
          method: squash
          strict_method: merge
        delete_head_branch: {}
        dismiss_reviews: {}
      conditions:
      - author=renovate[bot]
      - status-success=Semantic Pull Request
      - "status-success=ci/circleci: build-and-test"
      - -closed
